"""
Gold SQL + schema hints → NLQ 역생성 / 검토 스크립트
모든 단계를 순차 실행하고 하나의 CSV로 수합.

Usage:
  python scripts/generate_nlq_from_sql.py --model gpt-5.2-2025-12-11 --test_n 3
  python scripts/generate_nlq_from_sql.py --model gpt-5.2-2025-12-11
"""
import json, os, csv, argparse
from dotenv import load_dotenv
from openai import OpenAI
import google.generativeai as genai

load_dotenv()

# ── Step 1: llm_nlq (SQL → NLQ 생성) ─────────────────────────────
SYSTEM_GENERATE = """You are given a SQL query and schema hints (column mappings, join keys).
Your task: write a clear, natural English question that this SQL query answers.

Rules:
- The question should be something a business user would ask
- Include all the information needed to reconstruct the SQL (filters, aggregations, groupings, sorting)
- Do NOT mention table names or column names directly — use natural language equivalents from the Mappings
- Be specific about what is being asked (e.g., "list", "count", "total", "average", "for each")
- Output ONLY the question, nothing else"""

# ── Step 2/4: review (SQL 재구성 가능 여부 — LLM NLQ용) ──────────
SYSTEM_REVIEW = """You are given a SQL query, schema hints, and a natural language question (NLQ).
Your task: judge whether the NLQ contains enough information to reconstruct the SQL query.

Check:
- Are all WHERE filters mentioned in the NLQ?
- Are aggregation details clear (GROUP BY keys, aggregate functions)?
- Are JOIN relationships implied by the NLQ?
- Are sorting, DISTINCT, LIMIT, HAVING conditions reflected?
- Are window functions (OVER, PARTITION BY) described?

If the NLQ is sufficient to reconstruct the SQL:
  Reply with exactly: PASS

If the NLQ is missing information:
  Reply with the revised NLQ that adds the missing details.
  - Add missing information naturally into the question
  - Do NOT mention table/column names — use natural language from the Mappings
  - The revised NLQ MUST be in English
  - Output ONLY the revised question, nothing else"""

# ── Step 3: review (SQL 재구성 가능 여부 — Gold NLQ용, 표현 보존) ──
SYSTEM_REVIEW_GOLD = """You are given a SQL query, schema hints, and a human-written natural language question (NLQ).
Your task: judge whether this NLQ contains enough information to reconstruct the SQL query.

Check:
- Are all WHERE filters mentioned in the NLQ?
- Are aggregation details clear (GROUP BY keys, aggregate functions)?
- Are JOIN relationships implied by the NLQ?
- Are sorting, DISTINCT, LIMIT, HAVING conditions reflected?
- Are window functions (OVER, PARTITION BY) described?

If the NLQ is sufficient to reconstruct the SQL:
  Reply with exactly: PASS

If the NLQ is missing information:
  You MUST preserve the original NLQ's wording, tone, and sentence structure as much as possible.
  Only INSERT the missing details — do NOT rephrase, reorganize, or rewrite parts that are already correct.
  Treat the original NLQ as sacred text: copy it verbatim and only splice in the minimum additions needed.
  - The revised NLQ MUST be in English
  - Output ONLY the revised question, nothing else"""

# ── Step 4: humanistic review ─────────────────────────────────────
SYSTEM_HUMANISTIC = """You are given a SQL query, schema hints, and a natural language question (NLQ) that was generated by an AI to describe the SQL.

The generated NLQ may be overly technical or contain details that a real human user would never specify.
Your task: rewrite the NLQ as something a realistic, non-technical business user would actually ask.

Guidelines:
- Real users do NOT specify: DISTINCT, GROUP BY keys, window functions, JOIN types, ORDER BY direction, HAVING clauses
- Real users DO specify: what they want to see, who/what they're asking about, basic filters (department name, year, etc.)
- Real users use vague terms like "list", "show me", "how many", "what are the", "for each"
- Real users may omit implicit conditions that are "obvious" in the business context (e.g., ADDRESS_PURPOSE='STREET' when asking for street addresses)
- Keep the core intent of the question, but strip away SQL-specific details
- The result should sound like a Slack message or email from a non-technical colleague

If the NLQ already sounds natural and human-like:
  Reply with exactly: PASS

If the NLQ is too technical:
  Reply with the rewritten, human-friendly NLQ.
  - The revised NLQ MUST be in English
  - Output ONLY the revised question, nothing else"""

# ── Step 6: gold NLQ + llm_rev 절충 (비전문가 톤 유지 + 최소 보완) ──
SYSTEM_MID_HUMANISTIC = """You are given:
1. A "Gold NLQ" — a question written by a human (non-technical, may be vague or incomplete)
2. A "Technical NLQ" — a question generated by AI that captures all SQL details (may be overly technical)
3. The actual SQL query and schema hints

Your task: create a MINIMALLY REVISED version of the Gold NLQ.

Rules:
- Use the Gold NLQ as your base and preserve its casual, non-technical TONE and STYLE
- You may lightly rephrase for fluency, but do NOT rewrite from scratch or change the overall structure
- Only supplement with details from the Technical NLQ that are CRITICAL and completely missing
- Do NOT add SQL jargon (DISTINCT, GROUP BY, PARTITION BY, window functions, JOIN types, ORDER BY direction, HAVING, etc.)
- Add missing details using natural, casual language (e.g., "for each department" instead of "grouped by department")
- The result should still sound like a real person asking a question — not an AI-generated description of a SQL query
- If the Gold NLQ is already sufficient, reply with exactly: PASS
- The revised NLQ MUST be in English
- Output ONLY the revised question, nothing else"""


def build_hints(item):
    parts = []
    evidence = item.get('evidence', '')
    if evidence:
        parts.append(f"Evidence: {evidence}")
    mapping = item.get('mapping', {})
    if mapping:
        lines = [f"- '{k}' → {', '.join(v)}" for k, v in mapping.items()]
        parts.append("Mappings:\n" + "\n".join(lines))
    join_keys = item.get('join_keys', [])
    if join_keys:
        jstr = ", ".join([f"({p[0]} = {p[1]})" for p in join_keys])
        parts.append(f"Join Keys: {jstr}")
    return "\n\n".join(parts)


def prompt_generate(item):
    return f"""{build_hints(item)}

SQL:
```sql
{item['sql']}
```

Write the natural language question this SQL answers:"""


def prompt_review(item, nlq):
    return f"""{build_hints(item)}

SQL:
```sql
{item['sql']}
```

NLQ: {nlq}

Can the SQL be fully reconstructed from this NLQ + Mappings + Join Keys?
If yes, reply: PASS
If no, reply with the revised NLQ (in English):"""


def prompt_humanistic(item, nlq):
    return f"""{build_hints(item)}

SQL:
```sql
{item['sql']}
```

AI-generated NLQ: {nlq}

Rewrite this as a question a real non-technical user would ask.
If it already sounds natural, reply: PASS
Otherwise, reply with the rewritten question (in English):"""


def prompt_mid_humanistic(item, gold_nlq, technical_nlq):
    return f"""{build_hints(item)}

SQL:
```sql
{item['sql']}
```

Gold NLQ (human-written): {gold_nlq}

Technical NLQ (AI-generated, complete): {technical_nlq}

Create a minimally revised version of the Gold NLQ, supplementing only critical missing info from the Technical NLQ.
Keep the Gold NLQ's casual, non-technical tone.
If the Gold NLQ is already sufficient, reply: PASS
Otherwise, reply with the revised question (in English):"""


# ── LLM call helpers ─────────────────────────────────────────────
def call_openai(client, model, system, user):
    resp = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": user}
        ],
        temperature=0
    )
    return resp.choices[0].message.content.strip()


def call_gemini(gemini_model, system, user):
    full_prompt = f"{system}\n\n{user}"
    response = gemini_model.generate_content(full_prompt)
    if not response.parts:
        return "Error: Blocked or Empty Response"
    return response.text.strip()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--data", default="./data/beaver/dw/dw.json")
    parser.add_argument("--model", default="gpt-5.2-2025-12-11")
    parser.add_argument("--gemini_model", default=None, help="Gemini model for cross-model review (optional)")
    parser.add_argument("--cross_model", default="gpt-5.2-2025-12-11", help="Model for cross-model review (default: same as --model)")
    parser.add_argument("--test_n", type=int, default=None)
    parser.add_argument("--output", default="./analysis/nlq_analysis.csv")
    args = parser.parse_args()

    with open(args.data, 'r', encoding='utf-8') as f:
        dataset = json.load(f)
    if args.test_n:
        dataset = dataset[:args.test_n]

    # OpenAI client
    openai_client = OpenAI()

    # Gemini client (only if --gemini_model is specified)
    gemini_model = None
    if args.gemini_model:
        gemini_api_key = os.getenv("GEMINI_API_KEY")
        if gemini_api_key:
            genai.configure(api_key=gemini_api_key)
            gemini_model = genai.GenerativeModel(args.gemini_model)
            print(f"Cross-model review: Gemini ({args.gemini_model})")
        else:
            print("Warning: GEMINI_API_KEY not set, falling back to OpenAI for cross-model review")
    else:
        print(f"Cross-model review: OpenAI ({args.cross_model})")

    rows = []

    for i, item in enumerate(dataset):
        print(f"[{i+1}/{len(dataset)}] Processing...")
        gold_nlq = item['question']
        gold_sql = item['sql']

        # ── Step 1: llm_nlq (OpenAI: SQL → NLQ) ──
        llm_nlq = call_openai(openai_client, args.model, SYSTEM_GENERATE, prompt_generate(item))
        print(f"  1) llm_nlq: {llm_nlq[:150]}")

        # ── Step 2: llm_nlq_rev (OpenAI: 자기 검증) ──
        llm_rev_raw = call_openai(openai_client, args.model, SYSTEM_REVIEW, prompt_review(item, llm_nlq))
        llm_rev_pass = (llm_rev_raw == "PASS")
        llm_rev_nlq = "" if llm_rev_pass else llm_rev_raw
        print(f"  2) llm_nlq_rev: {'[PASS] 수정X' if llm_rev_pass else llm_rev_nlq[:150]}")

        # ── Step 3: gold_nlq_rev (OpenAI: gold NLQ 검증, 표현 보존) ──
        gold_rev_raw = call_openai(openai_client, args.model, SYSTEM_REVIEW_GOLD, prompt_review(item, gold_nlq))
        gold_rev_pass = (gold_rev_raw == "PASS")
        gold_rev_nlq = "" if gold_rev_pass else gold_rev_raw
        print(f"  3) gold_nlq_rev: {'[PASS] 수정X' if gold_rev_pass else gold_rev_nlq[:150]}")

        # ── Step 4: llm_nlq_rev_cross (cross-model 검증) ──
        if gemini_model:
            cross_rev_raw = call_gemini(gemini_model, SYSTEM_REVIEW, prompt_review(item, llm_nlq))
            cross_label = "gemini"
        else:
            cross_rev_raw = call_openai(openai_client, args.cross_model, SYSTEM_REVIEW, prompt_review(item, llm_nlq))
            cross_label = args.cross_model
        cross_rev_pass = (cross_rev_raw == "PASS")
        cross_rev_nlq = "" if cross_rev_pass else cross_rev_raw
        print(f"  4) llm_nlq_rev_cross ({cross_label}): {'[PASS] 수정X' if cross_rev_pass else cross_rev_nlq[:150]}")

        # ── Step 5: llm_nlq_humanistic (OpenAI: 현실적 사용자 관점) ──
        human_rev_raw = call_openai(openai_client, args.model, SYSTEM_HUMANISTIC, prompt_humanistic(item, llm_nlq))
        human_rev_pass = (human_rev_raw == "PASS")
        human_rev_nlq = "" if human_rev_pass else human_rev_raw
        print(f"  5) llm_nlq_humanistic: {'[PASS] 수정X' if human_rev_pass else human_rev_nlq[:150]}")

        # ── Step 6: gold_rev_llm_nlq_mid_humanistic (gold NLQ + llm_rev 절충) ──
        # Technical NLQ: Step 2에서 수정됐으면 수정본, PASS면 llm_nlq 원본
        technical_nlq = llm_nlq if llm_rev_pass else llm_rev_nlq
        mid_human_raw = call_openai(openai_client, args.model, SYSTEM_MID_HUMANISTIC,
                                    prompt_mid_humanistic(item, gold_nlq, technical_nlq))
        mid_human_pass = (mid_human_raw == "PASS")
        mid_human_nlq = "" if mid_human_pass else mid_human_raw
        print(f"  6) gold_rev_llm_nlq_mid_humanistic: {'[PASS] 수정X' if mid_human_pass else mid_human_nlq[:150]}")

        print()

        row = {
            "idx": i,
            "gold_sql": gold_sql,
            "gold_nlq": gold_nlq,
            "llm_nlq": llm_nlq,
            "llm_nlq_rev": llm_rev_nlq,
            "llm_nlq_rev_pass": llm_rev_pass,
            "gold_nlq_rev": gold_rev_nlq,
            "gold_nlq_rev_pass": gold_rev_pass,
            "llm_nlq_rev_cross": cross_rev_nlq,
            "llm_nlq_rev_cross_pass": cross_rev_pass,
            "llm_nlq_humanistic": human_rev_nlq,
            "llm_nlq_humanistic_pass": human_rev_pass,
            "gold_rev_llm_nlq_mid_humanistic": mid_human_nlq,
            "gold_rev_llm_nlq_mid_humanistic_pass": mid_human_pass,
        }
        rows.append(row)

    # ── 통계 ──
    n = len(rows)
    pass_cols = [
        "llm_nlq_rev_pass",
        "gold_nlq_rev_pass",
        "llm_nlq_rev_cross_pass",
        "llm_nlq_humanistic_pass",
        "gold_rev_llm_nlq_mid_humanistic_pass",
    ]
    print(f"=== Summary ({n} items) ===")
    for col in pass_cols:
        cnt = sum(1 for r in rows if r[col])
        label = col.replace("_pass", "")
        print(f"  {label:40s} PASS: {cnt}/{n} ({100*cnt/n:.1f}%)")

    # ── CSV 저장 ──
    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    with open(args.output, 'w', encoding='utf-8-sig', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=rows[0].keys())
        writer.writeheader()
        writer.writerows(rows)

    # ── JSON도 저장 ──
    json_path = args.output.replace('.csv', '.json')
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(rows, f, ensure_ascii=False, indent=2)

    print(f"\nSaved to {args.output} and {json_path}")


if __name__ == "__main__":
    main()
