-- Predicted SQL
SELECT DISTINCT
  fba.FCLT_BUILDING_KEY AS building_key,
  b.BUILDING_STREET_ADDRESS,
  fba.CITY,
  fba.STATE,
  fba.POSTAL_CODE
FROM FCLT_ROOMS r
JOIN FCLT_ORG_DLC_KEY odk ON odk.FCLT_ORGANIZATION_KEY = r.FCLT_ORGANIZATION_KEY
JOIN MASTER_DEPT_HIERARCHY mdh ON mdh.DLC_KEY = odk.DLC_KEY
JOIN FCLT_BUILDING_ADDRESS fba ON fba.FCLT_BUILDING_KEY = r.FCLT_BUILDING_KEY
JOIN BUILDINGS b ON b.BUILDING_KEY = fba.FCLT_BUILDING_KEY
WHERE mdh.DLC_NAME = 'History'
  AND fba.ADDRESS_PURPOSE = 'STREET'
===
-- Gold SQL
SELECT DISTINCT
  d.FCLT_BUILDING_KEY,
  e.BUILDING_STREET_ADDRESS,
  d.CITY,
  d.STATE,
  d.POSTAL_CODE
FROM FCLT_BUILDING_ADDRESS d
JOIN FCLT_ROOMS a ON a.FCLT_BUILDING_KEY = d.FCLT_BUILDING_KEY
JOIN FCLT_ORG_DLC_KEY b ON a.FCLT_ORGANIZATION_KEY = b.FCLT_ORGANIZATION_KEY
JOIN MASTER_DEPT_HIERARCHY c ON b.DLC_KEY = c.DLC_KEY
JOIN BUILDINGS e ON e.BUILDING_KEY = d.FCLT_BUILDING_KEY
WHERE lower(c.DLC_NAME) = lower('History')
  AND d.ADDRESS_PURPOSE = 'STREET'
